### PR TITLE
Update help_text.html with block element

### PR DESCRIPTION
**Pull request by jjsiman**
I think there was an intention here to have a `span` be the inline version and `small` be the block version for form help text. `small` is also an inline element and only works with `form-control` elements that are block level above them.

For example with checkboxes, the input element is inline and thus the help text is not rendered on a new line. BS5 examples how a `div` element for `form-text` anyways (https://getbootstrap.com/docs/5.1/forms/overview/) and the font size is handled via the class, so I think we should make that change here.

### CODE REVIEW

**Comment by hyshka** [comment]
@jjsiman Can you link a page where you've noticed this being an issue on our site?

**Comment by hyshka** [comment]
@jjsiman Can you link a page where you've noticed this being an issue on our site? It's hard to track down an inline checkbox with help text.

**Comment by jjsiman** [comment]
I noticed it in profile edit form checkboxes, mainly http://localhost:8000/profile/privacy after logging in as Clark Kent

**Review by hyshka — APPROVED** [review]
Awesome, thank you. Yea, this looks appropriate to me, nice find!

**Pull request merged**
